export const portfolioData = [
  {
    id: "groupware",
    title: "이모션 그룹웨어",
    desc: "반응형 웹/모바일웹 사이트 신규 구축",
    period: "2021.11~2022.01",
    type: "project",
    role: "PA",
    tags: ["React", "Styled Component", "Axios"],
  },
  {
    id: "ananti",
    title: "아난티 온라인 커머스 플랫폼",
    desc: "반응형 웹/모바일웹 사이트 신규 구축",
    period: "2021.06~2021.12",
    url: "https://eternaljourney.ananti.kr/index",
    type: "project",
    role: "PA",
    tags: ["jQuery", "gsap"],
  },
  {
    id: "hanafind",
    title: "하나금융 파트너 인슈어테크 플랫폼",
    desc: "적응형 앱/웹/모바일웹 신규 구축",
    period: "2021.11~2022.05",
    type: "project",
    role: "PA",
    tags: ["Vue"],
  },
  {
    id: "twd",
    title: "T World Direct Shop",
    desc: "운영 유지보수",
    period: "2021.06~2021.11",
    url: "https://shop.tworld.co.kr/shop/main",
    type: "maintain",
    role: "PA",
    tags: ["jQuery"],
  },
  {
    id: "jaju",
    title: "JAJU",
    desc: "웹/모바일웹 쇼핑몰 사이트 신규 구축",
    period: "2020.12~2021.06",
    url: "https://www.sivillage.com/jaju/main/initMain.siv",
    type: "project",
    role: "PA",
    tags: ["jQuery"],
  },
  {
    id: "wells",
    title: "교원웰스",
    desc: "웹/모바일웹 사이트 신규 구축",
    period: "2020.06~2020.11",
    url: "http://www.kyowonwells.com/",
    type: "project",
    role: "PA",
    tags: ["jQuery"],
  },
  {
    id: "toyota_compliments",
    title: "토요타",
    desc: "직원용 칭찬시스템 웹/모바일웹 사이트 신규 구축",
    period: "2019.09~2019.11",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "gc_imed",
    title: "GC IMED",
    desc: "모바일 웹 사이트 신규 구축",
    period: "2019.04~2019.08",
    url: "https://www.gcimed.com/main",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "yo_toyota",
    title: "토요타",
    desc: "고객용 하이브리드앱 신규 구축",
    period: "2018.10~2019.03",
    url: "https://play.google.com/store/apps/details?id=com.yo.toyota&gl=US&pli=1",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "golping",
    title: "골핑",
    desc: "웹/모바일웹 유지보수, 10주년 기념 이벤트 / 블랙골프데이 이벤트 / 신규 및 기존 이벤트 / 모바일 푸시기획전 등 퍼블리싱",
    period: "2018.01~2018.12",
    url: "https://golping.golfzon.com/",
    type: "maintain",
    role: "PL",
    tags: ["Vue", "jQuery"],
  },
  {
    id: "jaseng",
    title: "자생 한방병원",
    desc: "웹/모바일웹 유지보수, 메인 (Web/Mobile) 리뉴얼 / 레이아웃 리뉴얼 / 내 질환의 모든 것 카테고리 페이지 리뉴얼",
    period: "2018.01~2018.12",
    url: "https://www.jaseng.co.kr/",
    type: "maintain",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "gc_ballance",
    title: "GC밸런스 심리상담센터",
    desc: "웹/모바일웹 사이트 신규 구축",
    period: "2018.08~2018.10",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "snsys",
    title: "삼성기전",
    desc: "웹 사이트 신규 구축",
    period: "2018.07~2018.08",
    url: "http://www.snsys.net/",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "sangsangin",
    title: "상상인 저축은행",
    desc: "웹 사이트 신규 구축",
    period: "2018.04~2018.07",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "herit",
    title: "헤리트 해빛온 태양광시스템",
    desc: "대시보드 신규 구축",
    period: "2018.05~2018.06",
    type: "project",
    role: "PL",
    tags: ["chart.js", "jQuery"],
  },
  {
    id: "golfzon",
    title: "골프존 통합멤버십",
    desc: "웹 사이트 신규 구축",
    period: "2018.03~2018.04",
    url: "https://www.golfzoncommerce.com/",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "jawsfood",
    title: "죠스떡볶이",
    desc: "브랜드, 프랜차이즈 웹/모바일웹 사이트 신규 구축",
    period: "2017.12~2018.02",
    url: "http://www.jawsfood.com/",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "dreamline",
    title: "드림라인",
    desc: "웹 사이트 신규 구축",
    period: "2017.07~2017.07",
    url: "https://www.dreamline.co.kr/index.php",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "brown",
    title: "브라운교육 t4u",
    desc: "반응형 웹 사이트 신규 구축",
    period: "2017.04~2017.07",
    type: "project",
    role: "PA",
    tags: ["jQuery"],
  },
  {
    id: "smart",
    title: "스마트교복",
    desc: "웹/모바일웹 사이트 신규 구축",
    period: "2017.03~2017.04",
    type: "project",
    role: "PA",
    tags: ["jQuery"],
  },
];
