export const portfolioData = [
  {
    id: "groupware",
    imgUrl: "/logo-emotion.svg",
    bgUrl: "/bg-emotion.png",
    title: "이모션 사내 그룹웨어",
    desc: "반응형 웹사이트 신규 구축",
    period: "2021.11~2022.03",
    type: "project",
    role: "PA",
    tags: ["React", "Next.js", "Styled Component", "Axios"],
  },
  {
    id: "ananti",
    imgUrl: "/logo-ananti.svg",
    bgUrl: "/bg-ananti.png",
    title: "아난티 온라인 커머스 플랫폼",
    desc: "반응형 웹사이트 신규 구축",
    period: "2021.06~2021.12",
    url: "https://eternaljourney.ananti.kr/index",
    type: "project",
    role: "PA",
    tags: ["jQuery", "gsap"],
  },
  {
    id: "hanafind",
    isMobile: true,
    imgUrl: "/logo-fingle.png",
    bgUrl: "/bg-fingle.png",
    title: "하나금융 파트너 인슈어테크 플랫폼",
    desc: "적응형 앱/웹/모바일웹 신규 구축",
    period: "2021.11~2022.05",
    type: "project",
    role: "PA",
    tags: ["Vue"],
  },
  {
    id: "twd",
    imgUrl: "/logo-twd.png",
    bgUrl: "/bg-twd.png",
    title: "T World Direct Shop",
    desc: "운영 유지보수",
    period: "2021.06~2021.11",
    url: "https://shop.tworld.co.kr/shop/main",
    type: "maintain",
    role: "PA",
    tags: ["jQuery"],
  },
  {
    id: "jaju",
    imgUrl: "/logo-jaju.svg",
    bgUrl: "/bg-jaju.png",
    title: "JAJU",
    desc: "웹/모바일웹 쇼핑몰 사이트 신규 구축",
    period: "2020.12~2021.06",
    url: "https://www.sivillage.com/jaju/main/initMain.siv",
    type: "project",
    role: "PA",
    tags: ["jQuery"],
  },
  {
    id: "wells",
    imgUrl: "/logo-wells.svg",
    bgUrl: "/bg-wells.png",
    title: "교원웰스",
    desc: "웹/모바일웹 사이트 신규 구축",
    period: "2020.06~2020.11",
    url: "http://www.kyowonwells.com/",
    type: "project",
    role: "PA",
    tags: ["jQuery"],
  },
  {
    id: "toyota_compliments",
    imgUrl: "/logo-toyota.png",
    title: "토요타",
    desc: "직원용 칭찬시스템 웹/모바일웹 사이트 신규 구축",
    period: "2019.09~2019.11",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "gc_imed",
    isMobile: true,
    imgUrl: "/logo-gcimed.png",
    bgUrl: "/bg-gcimed.png",
    title: "GC IMED",
    desc: "모바일 웹 사이트 신규 구축",
    period: "2019.04~2019.08",
    url: "https://www.gcimed.com/main",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "yo_toyota",
    isMobile: true,
    imgUrl: "/logo-toyota.png",
    bgUrl: "/bg-yotoyota.png",
    title: "토요타",
    desc: "고객용 하이브리드앱 신규 구축",
    period: "2018.10~2019.03",
    url: "https://play.google.com/store/apps/details?id=com.yo.toyota&gl=US&pli=1",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "golping",
    imgUrl: "/logo-golping.png",
    bgUrl: "/bg-golping.png",
    title: "골핑",
    desc: "웹/모바일웹/vue앱 유지보수, 10주년 기념 이벤트 / 블랙골프데이 이벤트 / 신규 및 기존 이벤트 / 모바일 푸시기획전 / edm 등 고객의 요구에 맞춰 신속하고 정확하게 퍼블리싱 작업을 완료했습니다.",
    period: "2018.01~2018.12",
    url: "https://golping.golfzon.com/",
    type: "maintain",
    role: "PL",
    tags: ["Vue", "jQuery"],
  },
  {
    id: "jaseng",
    imgUrl: "/logo-jasaeng.svg",
    bgUrl: "/bg-jasaeng.png",
    title: "자생 한방병원",
    desc: "웹/모바일웹 유지보수, 메인 (Web/Mobile) 리뉴얼 / 레이아웃 리뉴얼 / 내 질환의 모든 것 카테고리 페이지 리뉴얼",
    period: "2018.01~2018.12",
    url: "https://www.jaseng.co.kr/",
    type: "maintain",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "gc_balance",
    imgUrl: "/logo-gc.png",
    title: "GC밸런스 심리상담센터",
    desc: "웹/모바일웹 사이트 신규 구축",
    period: "2018.08~2018.10",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "snsys",
    imgUrl: "/logo-snsys.png",
    bgUrl: "/bg-snsys.png",
    title: "삼성기전",
    desc: "웹 사이트 신규 구축",
    period: "2018.07~2018.08",
    url: "http://www.snsys.net/",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "sangsangin",
    imgUrl: "/logo-sangsangin.png",
    bgUrl: "/bg-sangsangin.png",
    title: "상상인 저축은행",
    desc: "웹 사이트 신규 구축",
    period: "2018.04~2018.07",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "herit",
    imgUrl: "/logo-herit.png",
    title: "헤리트 해빛온 태양광시스템",
    desc: "태양광 시스템 대시보드 신규 구축 프로젝트로, 전달받은 데이터를 그래프로 나타낼 수 있도록 chart.js를 사용했습니다.",
    period: "2018.05~2018.06",
    type: "project",
    role: "PL",
    tags: ["chart.js", "jQuery"],
  },
  {
    id: "golfzon",
    imgUrl: "/logo-golfzon.png",
    bgUrl: "/bg-golfzon.png",
    title: "골프존 통합멤버십",
    desc: "웹 사이트 신규 구축",
    period: "2018.03~2018.04",
    url: "https://www.golfzoncommerce.com/",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "jawsfood",
    imgUrl: "/logo-jaws.png",
    bgUrl: "/bg-jaws.png",
    title: "죠스떡볶이",
    desc: "브랜드, 프랜차이즈 웹/모바일웹 사이트 신규 구축",
    period: "2017.12~2018.02",
    url: "http://www.jawsfood.com/",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "dreamline",
    imgUrl: "/logo-dreamline.png",
    bgUrl: "/bg-dreamline.png",
    title: "드림라인",
    desc: "웹 사이트 신규 구축",
    period: "2017.07~2017.07",
    url: "https://www.dreamline.co.kr/index.php",
    type: "project",
    role: "PL",
    tags: ["jQuery"],
  },
  {
    id: "brown",
    title: "브라운교육 t4u",
    desc: "반응형 웹 사이트 신규 구축",
    period: "2017.04~2017.07",
    type: "project",
    role: "PA",
    tags: ["jQuery"],
  },
  {
    id: "smart",
    title: "스마트교복",
    desc: "웹/모바일웹 사이트 신규 구축",
    period: "2017.03~2017.04",
    type: "project",
    role: "PA",
    tags: ["jQuery"],
  },
];

export const gnbMenu = [
  {
    url: "/aboutme",
    title: "About Me",
  },
  {
    url: "/portfolio",
    title: "Portfolio",
  },
  {
    url: "/skills",
    title: "Skills",
  },
  {
    url: "/contact",
    title: "Contact",
  },
  {
    url: "/demo",
    title: "Scroll Event Demo",
  },
];

export const sns = [
  {
    type: "velog",
    url: "https://velog.io/@erun",
  },
  {
    type: "github",
    url: "https://github.com/Doeuning",
  },
];
